---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/5 18:23
---

---@class operation.OperationDecorator
---@field component operation.OperationComponent
local OperationDecorator = class("operation.OperationDecorator", require("operation.OperationComponent"))

function OperationDecorator:ctor(component)
    self:decorate(component)
end

function OperationDecorator:decorate(component)
    self.component = component
end

function OperationDecorator:getComponent()
    return self.component
end

---canHold
---@param unit unit.Unit
function OperationDecorator:canHold(unit)
    return self:checkHoldType(unit) and self:checkHoldWay(unit)
end

---checkHoldType
---@param unit unit.Unit
function OperationDecorator:checkHoldType(unit)
    return self.component:checkHoldType(unit)
end

---checkHoldWay
---@param unit unit.Unit
function OperationDecorator:checkHoldWay(unit)
    return self.component:checkHoldWay(unit)
end

---canAssistTrans
---@param unit unit.Unit
function OperationDecorator:canAssistTrans(unit)
    return self.component:canAssistTrans(unit)
end

---canTransAttack
---@param unit unit.Unit
function OperationDecorator:canTransAttack(unit)
    return self.component:canTransAttack(unit)
end

---canTransDefence
---@param unit unit.Unit
function OperationDecorator:canTransDefence(unit)
    return self.component:canTransDefence(unit)
end

---canDelete
---@param unit unit.UnitData
function OperationDecorator:canDelete(unit)
    return self.component:canDelete(unit)
end

return OperationDecorator
