---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/7 15:12
---

---@class operation.OperatorNormal:operation.OperationComponent
local OperatorNormal = class("operation.OperatorNormal", require("operation.OperationComponent"))

function OperatorNormal:getComponent()
    return nil
end

function OperatorNormal:setColor(value) end

function OperatorNormal:getColor() end

function OperatorNormal:hasColor() end

---canHold
---@param unit unit.Unit
function OperatorNormal:canHold(unit) end

function OperatorNormal:holdUp(unit) end

function OperatorNormal:putDown(unit) end

function OperatorNormal:canAssistTrans(unit) end

function OperatorNormal:canTransAttack(unit) end

function OperatorNormal:canTransDefence(unit) end

function OperatorNormal:canDelete() end

return OperatorNormal
