---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/6 14:37
---

---@class operation.OperationBase
local OperationBase = class("operation.OperationBase", require("operation.OperationComponent"))
---@type operation.OperationComponent
local super = OperationBase.super

return OperationBase
