---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/13 21:44
---

---@class operation.OperationUnitType:operation.OperationDecorator
local OperationUnitType = class("operation.OperationUnitType", require("operation.OperationDecorator"))

---canHold
---@param unit unit.Unit
function OperationUnitType:canHold(unit)
    return TypeOperations[unit.unitData.type].hold == 1 and self.component:canHold(unit)
end

---canAssistTrans
---@param unit unit.Unit
function OperationUnitType:canAssistTrans(unit)
    return TypeOperations[unit.unitData.type].assistTrans == 1
end

---canTransAttack
---@param unit unit.Unit
function OperationUnitType:canTransAttack(unit)
    return TypeOperations[unit.unitData.type].transAttack == 1
end

---canTransDefence
---@param unit unit.Unit
function OperationUnitType:canTransDefence(unit)
    return TypeOperations[unit.unitData.type].transDefence == 1
end

---canDelete
---@param unit unit.Unit
function OperationUnitType:canDelete(unit)
    return TypeOperations[unit.unitData.type].delete == 1
end

return OperationUnitType
