---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/6 14:04
---

---@class operation.OperationTransAttack
local OperationTransAttack = class("operation.OperationTransAttack", require("operation.OperationDecorator"))
---@type operation.OperationDecorator
local super = OperationTransAttack.super

function OperationTransAttack:ctor(component)
    super.ctor(self, component)
end

return OperationTransAttack
