---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/5 18:23
---

---@class operation.OperationDecorator
---@field component operation.OperationComponent
local OperationDecorator = class("operation.OperationDecorator", require("operation.OperationComponent"))

function OperationDecorator:ctor(component)
    self:decorate(component)
end

function OperationDecorator:decorate(component)
    self.component = component
end

function OperationDecorator:canHold()
    return nil
end

function OperationDecorator:getComponent()
    return self.component
end

return OperationDecorator
