---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/5 18:23
---

---@class operation.OperationComponent
local OperationComponent = class("operation.OperationComponent")

function OperationComponent:canHold()
    return false
end

function OperationComponent:getComponent()
    return nil
end

function OperationComponent:setColor(value)
    self.color = value
end

function OperationComponent:getColor()
    return self.color
end

function OperationComponent:hasColor()
    return true
end

return OperationComponent
