---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/6 12:20
---

---@class operation.OperationColor
local OperationColor = class("operation.OperationColor", require("operation.OperationDecorator"))
---@type operation.OperationDecorator
local super = OperationColor.super

function OperationColor:ctor(component)
    super.ctor(self, component)
end

function OperationColor:setColor(value)
    self.color = value
end

function OperationColor:getColor()
    return self.color
end

function OperationColor:hasColor()
    return true
end

return OperationColor
