---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/7 15:12
---

---@class operation.OperationNormal:operation.OperationComponent
local OperationNormal = class("operation.OperationNormal", require("operation.OperationComponent"))

---canHold
---@param unit unit.Unit
function OperationNormal:canHold(unit)
    return TypeOperations[unit.unitData.type].hold == 1
end

---canAssistTrans
---@param unit unit.Unit
function OperationNormal:canAssistTrans(unit)
    return TypeOperations[unit.unitData.type].assistTrans == 1
end

---canTransAttack
---@param unit unit.Unit
function OperationNormal:canTransAttack(unit)
    return TypeOperations[unit.unitData.type].transAttack == 1
end

---canTransDefence
---@param unit unit.Unit
function OperationNormal:canTransDefence(unit)
    return TypeOperations[unit.unitData.type].transDefence == 1
end

---canDelete
---@param unit unit.Unit
function OperationNormal:canDelete(unit)
    return TypeOperations[unit.unitData.type].delete == 1
end

return OperationNormal
