---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/6 12:20
---

---@class operation.OperationFormed
local OperationFormed = class("operation.OperationFormed", require("operation.OperationDecorator"))
---@type operation.OperationDecorator
local super = OperationFormed.super

function OperationFormed:ctor(component)
    super.ctor(self, component)
end
return OperationFormed
