---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/6 14:04
---

---@class operation.OperationTransDefence
local OperationTransDefence = class("operation.OperationTransDefence", require("operation.OperationDecorator"))
---@type operation.OperationDecorator
local super = OperationTransDefence.super

function OperationTransDefence:ctor(component)
    super.ctor(self, component)
end

return OperationTransDefence
