---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/6 14:05
---

---@class operation.OperationHold
local OperationHold = class("operation.OperationHold", require("operation.OperationDecorator"))
---@type operation.OperationDecorator
local super = OperationHold.super

function OperationHold:ctor(component)
    super.ctor(self, component)
end

return OperationHold
