---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/7 15:30
---

---@class Lineup
local Lineup = class("Lineup")

function Lineup:ctor(normal, special)

end

function Lineup:addCoreUnit()
    
end

function Lineup:addEliteUnit()

end

function Lineup:addChampionUnit()
    
end

return Lineup
