---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/4 10:41
---

---@class unit.ColorUnit:unit.UnitDecorator
local ColorUnit = class("unit.ColorUnit", require("unit.UnitDecorator"))
---@type unit.UnitDecorator
local super= ColorUnit.super
function ColorUnit:ctor(component)
    super.ctor(self.component)
end

function ColorUnit:setColor(color)
    self.color = color
end

function ColorUnit:getColor()
    return self.color
end

return ColorUnit
