---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/4 10:41
---

---@class unit.ColorUnit
---@field color number
local ColorUnit = class("unit.ColorUnit", require("unit.Unit"))
---@type unit.Unit
local super = ColorUnit.super
---ctor
---@param unitData unit.UnitData
---@param color number
function ColorUnit:ctor(unitData, color)
    super.ctor(unitData)
    self.color = color
end

function ColorUnit:getColor()
    return self.color
end

return ColorUnit
