---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/5 17:12
---

---@class unit.HoldableUnit:unit.UnitDecorator
local HoldableUnit = class("unit.HoldableUnit", require("unit.UnitDecorator"))
---@type unit.UnitDecorator
local super = HoldableUnit.super

function HoldableUnit:ctor(component)
    super.ctor(self, component)
end

return HoldableUnit
