---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/5 15:37
---

---@class unit.TransDefenceUnit:unit.UnitDecorator
local TransDefenceUnit = class("unit.TransDefenceUnit", require("unit.UnitDecorator"))
---@type unit.UnitDecorator
local super = TransDefenceUnit.super

function TransDefenceUnit:ctor(component)
    super.ctor(self, component)
end

function TransDefenceUnit:transDefence()

end

return TransDefenceUnit