---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/4 10:41
---

---@class unit.TransAttackUnit:unit.UnitDecorator
local TransAttackUnit = class("unit.TransAttackUnit", require("unit.UnitDecorator"))
---@type unit.UnitDecorator
local super = TransAttackUnit.super

function TransAttackUnit:ctor(component)
    super.ctor(self, component)
end

function TransAttackUnit:transAttack()

end

return TransAttackUnit
