---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/5 17:29
---

---@class unit.UnitDecorator:unit.UnitComponent
---@field component unit.UnitComponent
local UnitDecorator = class("unit.UnitDecorator", require("unit.UnitComponent"))

---ctor
---@param component unit.UnitComponent
function UnitDecorator:ctor(component)
    self:decorate(component)
end

---decorate
---@param component unit.UnitComponent
function UnitDecorator:decorate(component)
    self.component = component
end

function UnitDecorator:getComponent()
    return self.component
end

return UnitDecorator
