---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ukyohpq.
--- DateTime: 17/12/5 17:28
---

---@class unit.UnitComponent
local UnitComponent = class("unit.UnitComponent")

function UnitComponent:tostring()
    return nil
end

function UnitComponent:getSize()
    return nil
end

---setColor
---@param color number
function UnitComponent:setColor(color)
end

---@return number
function UnitComponent:getColor()
    return nil
end

---@return unit.UnitComponent
function UnitComponent:getComponent()
    return nil
end

return UnitComponent
